[workspace]
members = [
    "crates/sald-core",
    "crates/sald",
    "crates/sald-lsp",
    "crates/salad",
]
resolver = "2"

[workspace.package]
version = "0.4.0"
edition = "2021"
authors = ["starssxproject"]